[package]
name = "dusky-papers"
version = "1.1.0"
edition = "2024"
authors = ["Dusk Linux"]
description = "Dusky Papers: fast, lightweight wallpapers for Arch Linux / Hyprland"

[dependencies]
iced = { version = "0.14", default-features = false, features = ["advanced", "image-without-codecs", "wayland", "wgpu", "thread-pool"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp", "gif"] }
rayon = "1.10"
fastrand = "2.5"
sha2 = "0.10"
walkdir = "2.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
